module QuestionsModule
  STYLE_QUESTIONS = [
    "What is the most important aspect of your project?",
    "Can you summarize your idea in one word?",
    "How would you characterize your approach to this problem?",
    "Describe your concept using a single word.",
    "What word captures the essence of your idea?",
    "If you had to choose one word to convey your message, what would it be?",
    "What term best encapsulates your project?",
    "In a nutshell, what is the key concept of your idea?",
    "If your idea had a single-word tagline, what would it be?",
    "What's the core theme of your project in one word?",
    "Capture the essence of your idea with a single word.",
    "What word best represents the heart of your idea?",
    "Summarize your concept using just one word.",
    "What is the defining word for your project?",
    "If you had to label your idea with one word, what would it be?",
    "What word would you use to define the focus of your project?",
    "In a single word, express the main idea behind your project.",
    "If you had to choose a single word to describe your vision, what would it be?",
    "What word reflects the central theme of your idea?",
    "Describe your idea concisely with one word.",
    "Describe your artistic style in one word.",
    "What word captures the essence of your creative approach?",
    "In a single word, define your unique artistic expression.",
    "How would you characterize your design style?",
    "Summarize your creative style with one word.",
    "What term best represents your aesthetic vision?",
    "If you had to label your artistic style, what would it be?",
    "Express your design philosophy in one word.",
    "Define your visual style in a single word.",
    "Capture the spirit of your artistic expression with one word.",
    "How do you characterize your approach to design?",
    "What word best describes your creative signature?",
    "If your art had a one-word tagline, what would it be?",
    "Sum up your design style in one word.",
    "What adjective defines your artistic sensibility?",
    "If you had to use one word to convey your creative vibe, what would it be?",
    "Define your artistic identity with a single word.",
    "What word reflects the core of your design aesthetic?",
    "In one word, express the style of your creative work.",
    "What term resonates with your artistic expression?",
    "If you had to choose one word to describe your visual language, what would it be?",
    "Summarize your creative style using a single word.",
    "What adjective best captures the mood of your artwork?",
    "If your design had a one-word descriptor, what would it be?",
    "Express your creative identity in one word.",
    "How would you label your artistic style in a nutshell?",
    "Define your design approach with a single word.",
    "Sum up your visual style using one word.",
    "What word best embodies your creative aesthetic?",
    "If you had to distill your artistic essence into one word, what would it be?",
    "Express your design philosophy in a single word.",
    "Define your creative style using one word.",
    "In one word, describe the character of your artistic expression.",
    "Capture the essence of your design style with a single word.",
    "What term best encapsulates your visual language?",
    "Summarize your creative approach in one word.",
    "If you had to pick one word to represent your artistic vibe, what would it be?",
    "Define your design aesthetic with a single word.",
    "Express the mood of your creative work in one word.",
    "What word best characterizes your artistic identity?",
    "If your art had a one-word summary, what would it be?",
    "Sum up your creative style using a single word.",
    "What adjective defines the tone of your artistic expression?",
    "In one word, express the style of your design work.",
    "What term resonates with your creative vision?",
    "If you had to choose one word to describe your visual style, what would it be?",
    "Summarize your artistic identity in one word.",
    "What word reflects the essence of your design aesthetic?",
    "Define your creative approach with a single word.",
    "Express your design philosophy using one word.",
    "In one word, describe the character of your creative expression.",
    "Capture the core of your design style with a single word.",
    "What term best represents your artistic language?",
    "If you had to distill your visual identity into one word, what would it be?",
    "Define your creative style with a single word.",
    "Sum up the mood of your artistic work using one word.",
    "What word best embodies your design aesthetic?",
    "If you had to pick one word to convey your creative essence, what would it be?",
    "Express your artistic philosophy in one word.",
    "In a single word, define the style of your creative output.",
    "How would you characterize your artistic language?",
    "Summarize your design style in one word.",
    "What term best captures the soul of your creative work?",
    "If you had to label your artistic vibe with one word, what would it be?",
    "Define your visual identity with a single word.",
    "Capture the spirit of your design style in one word.",
    "What word reflects the core of your artistic aesthetic?",
    "In one word, express the style of your creative projects.",
    "If you had to choose one word to describe your design language, what would it be?",
    "Summarize your artistic approach using a single word.",
    "What adjective defines the atmosphere of your creative expression?",
    "If your design had a one-word descriptor, what would it be?",
    "Express your creative identity in one word.",
    "How would you label your artistic style in a nutshell?",
    "Define your design approach with a single word.",
    "Sum up your visual style using one word.",
    "What word best embodies your creative aesthetic?",
    "If you had to distill your artistic essence into one word, what would it be?",
    "Express your design philosophy in a single word.",
    "Define your creative style using one word.",
    "In one word, describe the character of your artistic expression.",
    "Capture the essence of your design style with a single word.",
    "What term best encapsulates your visual language?",
    "Summarize your creative approach in one word.",
    "If you had to pick one word to represent your artistic vibe, what would it be?",
    "Define your design aesthetic with a single word.",
    "Express the mood of your creative work in one word.",
    "What word best characterizes your artistic identity?",
    "If your art had a one-word summary, what would it be?",
    "Sum up your creative style using a single word.",
    "What adjective defines the tone of your artistic expression?",
    "In one word, express the style of your design work.",
    "What term resonates with your creative vision?",
    "If you had to choose one word to describe your visual style, what would it be?",
    "Summarize your artistic identity in one word.",
    "What word reflects the essence of your design aesthetic?",
    "Define your creative approach with a single word.",
    "Express your design philosophy using one word.",
    "In one word, describe the character of your creative expression.",
    "Capture the core of your design style with a single word.",
    "What term best represents your artistic language?",
    "If you had to distill your visual identity into one word, what would it be?",
    "Define your creative style with a single word.",
    "Sum up the mood of your artistic work using one word.",
    "What word best embodies your design aesthetic?",
    "If you had to pick one word to convey your creative essence, what would it be?",
    "Express your artistic philosophy in one word.",
    "In a single word, define the style of your creative output."
  ]
  

  GOALS_QUESTIONS = [
    "What are your primary objectives for the near future?",
    "Can you outline the key goals you've set for yourself?",
    "What targets are you aiming to achieve in the coming months?",
    "Describe your most important aspirations at the moment.",
    "What ambitions are currently driving your actions?",
    "What specific outcomes are you striving for in the short term?",
    "Highlight the major goals that you're actively pursuing.",
    "What milestones do you hope to reach in your journey?",
    "What key results are you committed to accomplishing soon?",
    "Outline the significant goals that guide your efforts.",
    "What do you envision accomplishing in the next few weeks?",
    "Can you succinctly state your top priorities and objectives?",
    "What important targets are on your radar right now?",
    "Define the primary goals that energize your daily activities.",
    "What specific achievements are you focused on in the immediate future?",
    "What outcomes are you determined to create in the upcoming period?",
    "Highlight the goals that currently shape your decision-making.",
    "What measurable results are you aiming to produce soon?",
    "Describe the major objectives that steer your actions.",
    "What are the core aspirations driving your efforts today?",
    "What specific aims are you actively pursuing at present?",
    "Can you list the key goals that define your current path?",
    "What outcomes are you resolved to bring about in your journey?",
    "Outline the primary targets you're working towards.",
    "What milestones do you anticipate reaching shortly?",
    "What key results are you committed to delivering in the near term?",
    "Describe your primary aspirations for the coming weeks.",
    "What specific goals are guiding your decision-making now?",
    "What measurable achievements are you striving for currently?",
    "Highlight the major objectives shaping your actions.",
    "What specific outcomes are you determined to achieve soon?",
    "What goals are at the forefront of your focus right now?",
    "Can you succinctly express the main objectives driving you?",
    "What are the key results you aim to produce in the near future?",
    "Outline the primary goals that define your current trajectory.",
    "What outcomes are you dedicated to creating in the next few weeks?",
    "Describe the major aspirations that fuel your daily efforts.",
    "What specific targets are you actively pursuing in your journey?",
    "Can you list the significant achievements you're aiming for soon?",
    "What goals are influencing your decision-making at present?",
    "What outcomes are you committed to bringing about in the immediate future?",
    "Highlight the primary objectives guiding your actions.",
    "What specific results are you determined to accomplish shortly?",
    "What milestones do you anticipate reaching in the near term?",
    "Describe your most important aspirations for the upcoming weeks.",
    "What measurable goals are you striving to achieve currently?",
    "What core objectives are shaping your decision-making now?",
    "Can you succinctly state the key results you're aiming for soon?",
    "What significant achievements are at the forefront of your focus right now?",
    "Outline the primary goals that define your current path.",
    "What outcomes are you dedicated to bringing about in the next few weeks?",
    "What specific targets are influencing your actions currently?",
    "Describe the major aspirations that guide your daily efforts.",
    "What goals are you actively pursuing in your journey?",
    "Can you list the key results you're committed to achieving soon?",
    "What measurable goals are you determined to accomplish shortly?",
    "Highlight the primary objectives that shape your decision-making.",
    "What specific outcomes are at the forefront of your focus right now?",
    "What core goals are you striving to achieve in the near future?",
    "What significant achievements are you dedicated to bringing about soon?",
    "Outline the major aspirations that define your current trajectory.",
    "What targets are guiding your actions in the next few weeks?",
    "Describe the primary objectives that fuel your daily efforts.",
    "What specific results are you actively pursuing at present?",
    "What goals are you committed to achieving in the upcoming period?",
    "Can you succinctly state the key outcomes you aim to produce soon?",
    "What milestones do you anticipate reaching in the immediate future?",
    "Highlight the specific achievements that shape your decision-making.",
    "What major aspirations are you determined to accomplish shortly?",
    "What outcomes are at the forefront of your focus in the near term?",
    "What goals are influencing your actions currently?",
    "Describe the key results that guide your daily efforts.",
    "What specific objectives are you striving to achieve in the upcoming weeks?",
    "Can you list the measurable goals you're committed to accomplishing soon?",
    "What core achievements are you dedicated to bringing about shortly?",
    "Outline the major goals that define your current path.",
    "What targets are you actively pursuing in the next few weeks?",
    "What specific outcomes are you committed to achieving at present?",
    "Highlight the primary aspirations that shape your decision-making.",
    "What results are you determined to produce in the near future?",
    "What goals are at the forefront of your focus in the upcoming period?",
    "Describe the key achievements that influence your daily efforts.",
    "What significant objectives are you striving to achieve shortly?",
    "What outcomes are you committed to bringing about at present?",
    "Can you succinctly state the major goals guiding your actions?",
    "What milestones do you anticipate reaching in the next few weeks?",
    "What specific results are you dedicated to accomplishing in the near term?",
    "What goals are influencing your decision-making currently?",
    "Describe the core aspirations that fuel your daily efforts.",
    "What specific achievements are you actively pursuing in your journey?",
    "Can you list the outcomes you're committed to bringing about shortly?",
    "What key goals are shaping your decision-making at present?",
    "Outline the major objectives that define your current trajectory.",
    "What targets are you determined to achieve in the upcoming weeks?",
    "What outcomes are guiding your actions in the near future?",
    "Highlight the primary goals that shape your decision-making.",
    "What specific results are you striving to accomplish shortly?",
    "What achievements are you committed to bringing about at present?",
    "Describe the major aspirations that influence your daily efforts.",
    "What goals are you actively pursuing in the next few weeks?",
    "Can you succinctly state the core outcomes you aim to produce soon?",
    "What milestones do you anticipate reaching in the immediate future?",
    "What specific objectives are you dedicated to achieving in the near term?",
    "Outline the key goals that define your current path.",
    "What can you tell me about your next creative project?",
    "How are you envisioning your upcoming artistic endeavor?",
    "What exciting ideas are brewing for your next creative venture?",
    "Can you share some insights into the inspiration behind your upcoming project?",
    "What themes or concepts are you exploring in your upcoming creative work?",
    "How do you plan to push the boundaries of your creativity in the next project?",
    "What sparked the genesis of your upcoming creative endeavor?",
    "In what ways will your next project reflect your unique artistic voice?",
    "Can you provide a glimpse into the creative process driving your upcoming work?",
    "What emotions or messages do you hope to convey through your next project?",
    "How does your upcoming project fit into the larger narrative of your creative journey?",
    "What challenges are you looking forward to tackling in your next creative pursuit?",
    "Are there specific mediums or techniques you're excited to experiment with in your next project?",
    "How do you anticipate your personal experiences shaping your upcoming creative expression?",
    "What role does collaboration play in your approach to your next creative venture?",
    "Can you describe the atmosphere or mood you aim to create with your upcoming project?",
    "What kind of impact or resonance do you hope your next project will have on your audience?",
    "How does your creative vision evolve from project to project?",
    "Are there any particular influences or artists inspiring your upcoming work?",
    "What significance does timing or context hold in the development of your next project?",
    "How do you see your upcoming creative endeavor contributing to your overall body of work?"
  ]


  def self.random_style_question
    STYLE_QUESTIONS.sample
  end

  def self.random_goal_question
    GOALS_QUESTIONS.sample
  end
end